export const FETCH_BOOKS_START = 'FETCH_BOOKS_START';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE';

export const FETCH_BOOK_BY_ID_START = 'FETCH_BOOK_BY_ID_START';
export const FETCH_BOOK_BY_ID_SUCCESS = 'FETCH_BOOK_BY_ID_SUCCESS';
export const FETCH_BOOK_BY_ID_FAILURE = 'FETCH_BOOK_BY_ID_FAILURE';

export const SEARCH_BOOK = 'SEARCH_BOOK';
